server:
  applicationConnectors:
      port: 8080
  adminConnectors:
      port: 8081

logging:
  level: INFO
  loggers:
    "org.example.MediQuery": DEBUG

metrics:
  reporters:
    - type: console
      frequency: 1 minute
